version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: kakadhaba_frontend
    restart: always
    ports:
      - "3000:80"

  backend:
    build: ./backend
    container_name: kakadhaba_backend
    restart: always
    environment:
      - MONGO_URI=${MONGO_URI}
    ports:
      - "5000:5000"

  reverse-proxy:
    image: nginx:alpine
    container_name: kakadhaba_proxy
    restart: always
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"